#
# Dockerfile for WordPress
#
FROM ubuntu:16.04
LABEL maintainer "v-jifan@microsoft.com"

# apache
ENV APACHE_VERSION 2.4.25

# php
ENV PHP_VERSION 7.1.1

# wordpress
ENV WORDPRESS_VERSION 4.7.2

# mysql
ENV MYSQL_VERSION 5.7.17

# phpMyAdmin
ENV PHPMYADMIN_VERSION 4.6.6

# redis
ENV REDIS_VERSION 3.2.7